### ISSUE TITLE
📅 5/25 @ 11am PT - 30 Minutes to Merge: Automating nose booping using Actions with @github

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#18]
💁🏻 **30 Minutes to Merge: Automating nose booping using Actions**
📅 Tuesday, May 25, 2021
🕐 11:00am Pacific Time ([in your timezone](https://everytimezone.com/s/6dc32c00))
🎙️ hosted by @github ([github.community event](https://github.community/t/30-minutes-to-merge-github-automation-11-am-pst/177632))
🏷️ Automation, Actions

---

Subscribe to this issues to get a notification before the show begins and a summary after the show concludes.

This will be a a follow to the show on learnwithjason.dev: https://www.learnwithjason.dev/github-automation-with-octokit ([video](https://youtu.be/H1TupRbbjSI), see also #11)

Together with @jlengstorf, we created a CLI to bump a nose-boop counter on Jason's GitHub profile page at https://github.com/jlengstorf/. We created a CLI and published it to npm. You can run it with `npx boop-jasons-nose`. It will create an issue in https://github.com/jlengstorf/jlengstorf.

We then created a GitHub App and deployed it to [Netlify functions](https://ntl.fyi/functions). The app receives webhook requests for new issues, and then is using its own credentials to bump the nose-boop counter ([function source code](https://github.com/learnwithjason/boop-jasons-nose/blob/main/netlify/functions/handle-issue.js)).

We planned to use GitHub Actions, but Actions experienced problems at the time of the show, so we skipped that part and used a GitHub App instead. 

#### Outline

- [x] Quick recap of what we did during [the Learn With Jason  show](https://www.learnwithjason.dev/github-automation-with-octokit). See [gr2m/boop-gregors-nose](https://github.com/gr2m/boop-gregors-nose). The relevant bit we want to automate with GitHub Actions is: for each newly created issue, bump the nose-boop counter by one.
- [x] Create a GitHub Action with Node.js + Octokit
  - [x] pull request: https://github.com/gr2m/boop-gregors-nose/pull/7
  - [x] create `.github/workflows/boop.yml` and run `cli.js`
  - [x] replace `cli.js` with `action.js` and authenticate using `GITHUB_TOKEN`
- [x] Make the action available to others
  - [x] Create `action.yml` - use `personal-access-token` input
  - [x] Bundle code and all dependencies using https://github.com/vercel/ncc
  - [x] Setup continuous deployments using @semantic-release
- [x] Publish the action to the Marketplace

<a name="recording"></a>
#### Recording

<a href="https://www.youtube.com/watch?v=H7CRtal714Q&feature=youtu.be""><img width="1281" alt="image" src="https://user-images.githubusercontent.com/39992/119913236-3d147700-bf12-11eb-88fe-a938f578f279.png">
</a>

<a name="shownotes"></a>
#### Shownotes

- Find the action we created and published during the show at https://github.com/marketplace/actions/boop-gregor-s-nose
- Source code: https://github.com/gr2m/boop-gregors-nose
- Test repository: https://github.com/gr2m/boop-gregors-nose-test
- GitHub Documentation:
  - [Events that Trigger GitHub Actions](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release)
- We used [`octokit`](https://github.com/octokit/octokit.js/) for sending requests to update the README and to create issues.
- We used [`@octokit/auth-oauth-device`](https://github.com/octokit/auth-oauth-device.js) as the authentication strategy in the CLI
- We used [`@actions/core`](https://github.com/actions/toolkit/tree/main/packages/core#readme) to read the `personal-access-token` input from GitHub Actions Workflows
- We used @semantic-release for release automation (see [workflow](https://github.com/gr2m/boop-gregors-nose/blob/be4dd6a3a4dcba1a007ad94c1be32fbf75ac5690/.github/workflows/release.yml))

#### Todos

- [x] Prepare a repository with a nose boop counter
- [x] re-create the CLI to bump the counter as we did with Jason in https://www.learnwithjason.dev/github-automation-with-octokit
- [x]  schedule a start of show tweet
- [ ]  tweet when recording is available

**Comment by gr2m** [comment]
The recording of the show is now on Twitch: https://www.twitch.tv/videos/1034907775

<a href="https://www.twitch.tv/videos/1034907775"><img width="1341" alt="image" src="https://user-images.githubusercontent.com/39992/119554891-11e32980-bd52-11eb-9cae-751991dba4d2.png"></a>

**Comment by gr2m** [comment]
The recording is now archived on YouTube: https://youtu.be/H7CRtal714Q

<a href="https://youtu.be/H7CRtal714Q""><img width="1281" alt="image" src="https://user-images.githubusercontent.com/39992/119913236-3d147700-bf12-11eb-88fe-a938f578f279.png">
</a>
