### ISSUE TITLE
📅 5/27 @ 1pm PT - transfer issues + comments between repositories while retaining authorship, labels, and milestones

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#20]
💁🏻 **transfer issues + comments between repositories while retaining authorship, labels, and milestones**
📅 Wednesday, May 27, 2021
🕐 1:00pm Pacific Time ([in your timezone](https://everytimezone.com/s/6fc05429))
🎙️ _let me know if you'd like to join_
🏷️ Automation

---

### transfer issues + comments between repositories while retaining authorship, labels, and milestones

This show is a follow up to the idea described at https://github.com/gr2m/helpdesk/issues/12 and [the show from May 20th](https://github.com/gr2m/helpdesk/issues/16) where we created a script to copy a repository including issues, comments, milestones, and labels. With the script from last week we will be able to quickly create repositories we can use to test this show's script.

<a name="outline"></a>
#### Outline

- [x] Recap the script created in #16 and use it to create two repositories for testing: source and target
  - https://github.com/Another-Practice-Organization
  - https://github.com/gr2m/copy-repository
  - https://create-user-to-server-token.netlify.app/ (create tokens using credentials of https://github.com/apps/another-practice-org-tokens)
  - Create test repository for source
  
    ```
    GITHUB_TOKENS=$COPY_REPOSITORY_GITHUB_TOKENS SOURCE_REPO=Another-Practice-Organization/template-issues-source npx copy-repository
    ```

    Create test repository for target

    ```
    GITHUB_TOKENS=$COPY_REPOSITORY_GITHUB_TOKENS SOURCE_REPO=Another-Practice-Organization/template-issues-target npx copy-repository
    ```

  - Delete test repositories

    ```
    octoherd-script-delete-repository \
      -T $GITHUB_TOKEN_DELETE_REPO \
      -R "Another-Practice-Organization/template-issues-source-copy-*" "Another-Practice-Organization/template-issues-target-copy-*"
    ```
- [x] Transfer all issues source to target
- [x] Make sure the same labels are applied. Create labels that are missing
- [x] Make sure the same milestones are applied. Create Milestones if they are missing

<a name="recording"></a>
#### Recording

_will be added after the show_

<a name="shownotes"></a>
#### Shownotes

_will be added after the show_

#### Preparation

- [ ]  30 minute announcement tweet
- [ ]  start of show tweet
- [ ]  comment on issue
- [ ]  recording available tweet

**Comment by gr2m** [comment]
now live on https://www.twitch.tv/gregorcodes

**Comment by gr2m** [comment]
# 🤦🏼  My mic was muted the whole time

here is the video anyway if you are interested: https://www.twitch.tv/videos/1037245669

You can find the code from this episode at https://github.com/gr2m/transfer-issues/

I'm not going to archive this repository on YouTube because it's embarrassing ... ugh
