### ISSUE TITLE
📅 6/24 @ 1pm PT - How to update lock files silently (Part III)

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#32]
💁🏻 **How to update lock files silently (Part III)**
📅 Thursday, June 24, 2021
🕐 1:00pm Pacific Time ([in your timezone](https://everytimezone.com/s/44c9d6cc))
🎙️ no guests
🏷️ Automation

---

Subscribe to this issues to get a notification before the show begins and a summary after the show concludes.

### How to update lock files silently (Part III)

This show is a follow up to https://github.com/gr2m/helpdesk/issues/24.

#### Outline

- [ ] Run a GitHub Action workflow each time commit status and check runs are set on a commit in the `lockfile-update` branch. Determine whether the status is green based on the branch protection settings.
- [ ] If any check failed, create a pull request. If all required checks are green, merge and delete the `lockfile-update` branch.

#### TODOs

Before the show

- [ ]  30 minute announcement tweet
- [ ]  30 minute announcement comment

When show begins

- [x]   start of show tweet
 (https://twitter.com/gr2m/status/1408152570909151246)
- [x]  comment on issue
 (https://github.com/gr2m/helpdesk/issues/32#issuecomment-867912862)
- [x]  Set twitter profile url to https://twitch.tv/gregorcodes
 (https://twitter.com/gr2m)

After the show

- [ ]  Reset twitter profile after the show
- [ ]  recording available tweet

<a name="recording"></a>
#### Recording

_will be added after the show_

<a name="shownotes"></a>
#### Shownotes

_will be added after the show_

**Comment by gr2m** [comment]
I'm now live on https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
Show is done for today, thank you all! Recording is coming up in a moment

**Comment by gr2m** [comment]
Recording is now available on Twitch:
https://www.twitch.tv/videos/1066497093
