### ISSUE TITLE
📅 6/28 @ noon PT - Automating gr2m/helpdesk: issue forms

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#34]
💁🏻 **Automating gr2m/helpdesk: issue forms**
📅 Monday, June 28, 2021
🕐 12:05pm Pacific Time ([in your timezone](https://everytimezone.com/s/0ae6f76c))
🎙️ no guests
🏷️ Automation

---

Subscribe to this issues to get a notification before the show begins and a summary after the show concludes.

### Automating gr2m/helpdesk: issue forms

After focusing on automating README updates, issue comments and tweets in the previous [automating helpdesk shows](https://github.com/gr2m/helpdesk/issues?q=is%3Aclosed+label%3A%22automating+helpdesk%22), I'll work this week on the newly announced [issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/).

Instead of creating new show issue by copying previous ones, it's about time to streamline the process. Maybe issue forms are not ideal for that purpose, but it's better than what I have right now and it will be fun to explore it.

#### Outline

1. Walk through the [new markdown issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-templates) and how they work
2. Show the two templates created for this repository: one for show ideas suggest by y'all, and the other a show template that is for my own shows.

#### TODOs

Before the show

- [ ] Prepare two show templates: one for show ideas, one for actual shows.
- [x]  30 minute announcement tweet
 (https://twitter.com/gr2m/status/1409584061673218052)
- [x]  30 minute announcement comment
 (https://github.com/gr2m/helpdesk/issues/34#issuecomment-869930860)

When show begins

- [x]    start of show tweet
 (https://twitter.com/gr2m/status/1409588976457969666)
- [x]  comment on issue
 (https://github.com/gr2m/helpdesk/issues/34#issuecomment-869946087)
- [x]  Set twitter profile url to https://twitch.tv/gregorcodes
 (https://twitter.com/gr2m)

After the show

- [ ]  Reset twitter profile after the show
 (https://twitter.com/gr2m)
- [ ]  recording available tweet

<a name="recording"></a>
#### Recording

_will be added after the show_

<a name="shownotes"></a>
#### Shownotes

_will be added after the show_

**Comment by gr2m** [comment]
Going live in 30 minutes at https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
I'm now live on https://twitch.tv/gregorcodes
