### ISSUE TITLE
📅 7/30 @ 9am PT - Running scheduled GitHub App tasks using Actions

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#38]
💁🏻 **Running scheduled GitHub App tasks using Actions**
📅 Friday, July 30, 2021
🕐 9:00am Pacific Time ([in your timezone](https://everytimezone.com/s/545d0e0c))
🎙️ Hosted by @bdougie
📍 https://www.twitch.tv/github
🏷️ Automation

---

Subscribe to this issues to get a notification before the show begins and a summary after the show concludes. You can also sign up for the event on https://www.meetup.com/Open-Sauced-Meetup/events/279608849

### Running scheduled GitHub App tasks using Actions

[opensauced.pizza](https://opensauced.pizza/) is your dashboard to plan and track your Open Source contributions. It works by forking the [open-sauced/goals-template](https://github.com/open-sauced/goals-template) repository, which includes the [`goals-caching.yml`](https://github.com/open-sauced/goals-template/blob/79e7ca214f9c7d128e237de3133b8b0655957443/.github/workflows/goals-caching.yml) workflow to synchronize data every two days. Besides the workflow, the [@open-sauced app](https://github.com/apps/Open-Sauced) is installed as well which acts on direct interactions with the repository. 

In this show, we will try to remove the  `goals-caching.yml` workflow from the template repository, and instead do the synchronization with the app, which is already installed. Apps do not have a native schedule trigger such as actions, but we can utilize a GitHub Action to authenticate as the app, and synchronize all repositories the app is installed on in one go.

<a name="outline"></a>
### Outline

- show the current flow
  - Add a new repository, star repository, show out-of-sync stars in open sauced dashboard. Run sync using the scheduled sync action by adding a `workflow_dispatch` trigger
- create sync flow using GitHub App
  - Create new workflow in [`open-sauced/open-sauced`](https://github.com/open-sauced/open-sauced) with a schedule trigger. 
  - We will need to put a `update-open-sauced-goals-cache.js` somewhere in the repository, and we need to install [`octokit`](https://github.com/octokit/octokit.js/) as dependency. We'll need to checkout the repository and setup Node 16 before running the script.
  - In the script, we will iterate all repositories of each installation. Load the `data.json` file for each repository, load the latest stats for each repository, then update the `data.json` file if there is any change.
  - Use [`@octokit/plugin-create-or-update-text-file`](https://github.com/octokit/plugin-create-or-update-text-file.js/) to simplify the process of loading and updating the files
  - Optimization: batch load statistics for 100 repositories at once using a single GraphQL query
- Bonus
  - create a script that creats pull request to all existing `*/open-sauced-goals` repositories which removes the `scheduled-caching.yml` workflow file using [`octokit-plugin-create-pull-request`](https://github.com/gr2m/octokit-plugin-create-pull-request)

### TODOs

Before the show

- [ ] @bdougie add GitHub App credentials of [Open Sauced GitHub App](https://github.com/apps/Open-Sauced) to the [`open-sauced/open-sauced`](https://github.com/open-sauced/open-sauced)  repository by setting `OPEN_SAUCED_APP_ID` and `OPEN_SAUCED_PRIVATE_KEY`
- [x]  30 minute announcement tweet
 (https://twitter.com/gr2m/status/1421132031413604354)
- [x]  30 minute announcement comment
 (https://github.com/gr2m/helpdesk/issues/38#issuecomment-889973105)

When show begins

- [x]    start of show tweet
 (https://twitter.com/gr2m/status/1421138052399960064)
- [x]  comment on issue
 (https://github.com/gr2m/helpdesk/issues/38#issuecomment-889987628)
- [x]  Set twitter profile url to https://twitch.tv/gregorcodes
 (https://twitter.com/gr2m)

After the show

- [ ]  Reset twitter profile after the show
- [ ]  recording available tweet

<a name="recording"></a>
### Recording

_will be added after the show_

<a name="shownotes"></a>
### Shownotes

_will be added after the show_

**Comment by gr2m** [comment]
Going live in 30 minutes at https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
I'm now live on https://twitch.tv/BdougieYO

**Comment by gr2m** [comment]
The show is done, I'll post a link once @bdougie uploads the video to YouTube

**Comment by gr2m** [comment]
Show is done for today, thank you all! Recording is coming up in a moment
