### ISSUE TITLE
📅 8/5 @ 10am PT - Automating gr2m/helpdesk: issue forms part II

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#42]
💁🏻 **Automating gr2m/helpdesk: issue forms - part II**
📅 Thursday, August 5, 2021
🕐 10:00am Pacific Time ([in your timezone](https://everytimezone.com/s/703bc3ad))
🎙️ no guests
📍 https://www.twitch.tv/gregorcodes
🏷️ Automation

---

Subscribe to this issues to get a notification before the show begins and a summary after the show concludes.

### Automating gr2m/helpdesk: issue forms part II

In [the first part](https://github.com/gr2m/helpdesk/issues/34) of the series on using issue forms in this repository, I used @stefanbuck's https://github.com/stefanbuck/github-issue-parser to parse the newly created issue but ran into some problems. In this episode I'll debug that problem with the goal to parse all the information from the form and update the issue body using a custom template.

#### Outline

1. Show the issue forms I created for this repository and the problem I ran into with the parsing
2. Debug and hopefully resolve the problem
3. Define a custom template and use it to update the issue body

#### TODOs

Before the show

- [ ] Prepare two show templates: one for show ideas, one for actual shows.
- [x]  30 minute announcement tweet
 (https://twitter.com/gr2m/status/1423322723103674372)
- [x]  30 minute announcement comment
 (https://github.com/gr2m/helpdesk/issues/42#issuecomment-893602803)

When show begins

- [x]     start of show tweet
 (https://twitter.com/gr2m/status/1423329525618733057)
- [x]  comment on issue
 (https://github.com/gr2m/helpdesk/issues/42#issuecomment-893620491)
- [x]  Set twitter profile url
 (https://twitter.com/gr2m)

After the show

- [ ]  Reset twitter profile after the show
- [ ]  recording available tweet

<a name="recording"></a>
#### Recording

_will be added after the show_

<a name="shownotes"></a>
#### Shownotes

_will be added after the show_

**Comment by gr2m** [comment]
Going live in 30 minutes at https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
I'm now live on https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
Sorry no recording today because I was muted for half the show 🤦🏼

**Comment by gr2m** [comment]
Show is done for today, thank you all! Recording is coming up in a moment
