### ISSUE TITLE
📅 8/19 @ 10:00am PT - Creating tests for actions for faster iteration

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#46]
💁🏻 **Automating gr2m/helpdesk: Creating tests for actions for faster iteration**
📅 Thursday, August 19, 2021
🕐 10:00am Pacific Time
🎙️ _no guests_
📍 https://www.twitch.tv/gregorcodes
🏷️ testing

---

Subscribe to this issues to get a notification before the show begins and a summary after the show concludes.

### Creating tests for actions for faster iteration

Creating tests for local actions is a huge time saver. It enables quick iteration and avoid regressions once problems occur.

#### Outline

I will create tests for the existing actions in this repository

#### TODOs

Before the show

- [x]  30 minute announcement tweet (https://twitter.com/gr2m/status/1428396668236574723)
- [x]  30 minute announcement comment (https://github.com/gr2m/helpdesk/issues/46#issuecomment-902071346)

When show begins

- [x]      start of show tweet (https://twitter.com/gr2m/status/1428404047254544386)
- [x]  comment on issue (https://github.com/gr2m/helpdesk/issues/46#issuecomment-902090820)
- [x]  Set twitter profile url (https://twitter.com/gr2m)

After the show

- [ ]  Reset twitter profile after the show
- [ ]  recording available tweet

<a name="recording"></a>
#### Recording

_will be added after the show_

<a name="shownotes"></a>
#### Shownotes

_will be added after the show_

**Comment by gr2m** [comment]
Going live in 30 minutes at https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
I'm now live on https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
It's a wrap! See you next week: https://github.com/gr2m/helpdesk/issues/47

**Comment by gr2m** [comment]
Show is done for today, thank you all! Recording is coming up in a moment

**Comment by gr2m** [comment]
Recording is up on twitch:

<a href="https://www.twitch.tv/videos/1123174994"><img width="963" alt="image" src="https://user-images.githubusercontent.com/39992/130120955-226dc37f-c7d1-445c-bdfa-f319fd439920.png"></a>

**Comment by gr2m** [comment]
Recording is now available on youtube:
<a href="https://www.youtube.com/watch?v=M0RaoVz6_DQ"><img width="1281" alt="image" src="https://user-images.githubusercontent.com/39992/130132049-e8b9200f-97a3-4189-98b8-f8cff4542b7e.png"></a>
