### ISSUE TITLE
📅 9/2 @ 10:00am PT - Creating tests for actions for faster iteration Part III

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#49]
💁🏻 **Creating tests for actions for faster iteration Part III**
📅 Thursday, September 2, 2021
🕐 10:00am Pacific Time
🎙️ _no guests_
📍 https://www.twitch.tv/gregorcodes
🏷️ testing

---

Subscribe to this issues to get a notification before the show begins and a summary after the show concludes.

### Creating tests for actions for faster iteration Part III

Part III of #46 and #47. I will continue adding tests for the existing scripts

#### Outline

undefined

#### TODOs

Before the show

- [x]  30 minute announcement tweet (https://twitter.com/gr2m/status/1433469247938772995)
- [x]  30 minute announcement comment (https://github.com/gr2m/helpdesk/issues/49#issuecomment-911866574)

When show begins

- [x]      start of show tweet (https://twitter.com/gr2m/status/1433476479535419396)
- [x]  comment on issue (https://github.com/gr2m/helpdesk/issues/49#issuecomment-911888652)
- [x]  Set twitter profile url (https://twitter.com/gr2m)

After the show

- [ ]  Reset twitter profile after the show
- [ ]  recording available tweet

<a name="recording"></a>

#### Recording

_will be added after the show_

<a name="shownotes"></a>

#### Shownotes

_will be added after the show_

**Comment by gr2m** [comment]
Going live in 30 minutes at https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
I'm now live on https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
I'm now live on https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
It's a wrap! 

You can find the raw recording at https://www.twitch.tv/videos/1136959254, I'll create a highlight to cut out the intro

**Comment by gr2m** [comment]
Show is done for today, thank you all! Recording is coming up in a moment

**Comment by gr2m** [comment]
The recording is now up on Twitch:

<a href="https://www.twitch.tv/videos/1137028333"><img width="860" alt="image" src="https://user-images.githubusercontent.com/39992/131897772-5fc4df3f-56fb-4cb2-b652-cb8ad3167699.png"></a>
