### ISSUE TITLE
📅 10/21 @ 10:00am PT - Automating gr2m/helpdesk: Twitch Events

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#52]
💁🏻 **Automating gr2m/helpdesk: Twitch Events**
📅 Thursday, October 21, 2021
🕐 10:00am Pacific Time
🎙️ _no guests_
📍 https://www.twitch.tv/gregorcodes
🏷️ automation

---

Subscribe to this issues to get a notification before the show begins and a summary after the show concludes.

### Automating gr2m/helpdesk: 📅 10/21 @ 10:00am PT - Automating gr2m/helpdesk: Twitch Events

Instead of using a schedule-based trigger for when a show starts, I'll start using webhooks sent from Twitch itself, whenever I start a stream.

#### Outline

- [x] Create a new repository `handle-twitch-events-using-github-actions` with a [Netlify Function](https://www.netlify.com/products/functions/) that responds to `/.netlify/functions/ping`
- [x] Setup continuous deployment of the repository using Netlify's GitHub App
- [x] Add a script to list, create, and delete Twitch subscriptions
- [x] Add a Netlify Function that will handle [Twitch EventSub](https://dev.twitch.tv/docs/eventsub) requests at `POST /.netlify/functions/twitch` and create [repository dispatch](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#repository_dispatch) events
- [x] Add a GitHub Action that gets triggered by the repository dispatch events

Bonus

- In the `gr2m/helpdesk` repository, rreplace the current schedule trigger for the [Handle show start workflow](https://github.com/gr2m/helpdesk/blob/main/handle-show-start.js) with the custom trigger when the webhook is received
- Replace the current `issues.closed` trigger for the [Handle show done workflow](https://github.com/gr2m/helpdesk/blob/main/.github/workflows/handle-show-done.yml) with the custom trigger when the webhook is received. Close the show issue

#### TODOs

Before the show

I already setup the Netlify function and the twitch subscription in the `gr2m/helpdesk`. I'll prepare the pieces so we can create a new repository from scratch step-by-step.

- [x]  30 minute announcement tweet
 (https://twitter.com/gr2m/status/1451227071120818183)
- [x]  30 minute announcement comment
 (https://github.com/gr2m/helpdesk/issues/52#issuecomment-948790453)

When show begins

- [x]      start of show tweet
 (https://twitter.com/gr2m/status/1451233334537895937)
- [x]  comment on issue
 (https://github.com/gr2m/helpdesk/issues/52#issuecomment-948819727)
- [x]  Set twitter profile url
 (https://twitter.com/gr2m)

After the show

- [x]  Reset twitter profile after the show
 (https://twitter.com/gr2m)
- [x]  recording available tweet

<a name="recording"></a>

#### Recording

<a href="https://youtu.be/hRFcaAeXJ9I"><img width="1284" alt="screenshot of YouTube video player showing the recording of this episode" src="https://user-images.githubusercontent.com/39992/138341450-44f1813f-0f30-4b77-914c-16184be5ce42.png"></a>

<a name="shownotes"></a>

#### Shownotes

- Demo repository I created during the show: https://github.com/gr2m/handle-twitch-events-using-github-actions
- Netlify CLI: https://docs.netlify.com/cli/get-started/
  I used `netlify dev` to start a local server, `netlify dev --live` to start a local server with an http tunnel, so it's reachable by others, and `netlify init` to setup continuous deployment for the demo repository using Netlify
- Twitch CLI: https://github.com/twitchdev/twitch-cli#readme
  - Send request to test subscription verification. `-F` is the URL the simulated webhook request should be sent to.
    ```
    twitch event verify-subscription subscribe -F http://localhost:8888/.netlify/functions/twitch
    ```
  - Get user account ID by login. You'll need your Twitch User Account ID to set the condition when creating the Twitch event subscription
    ```
    twitch api get users -q login=gregorcodes
    ```
  - Trigger a "stream.online" event. `-s` is the secret you defined when you created the subscription. `-t` is your account ID.
    ```
    twitch event trigger streamup -F http://localhost:8888/.netlify/functions/twitch -s secret -t 581268875
    ```
  - Trigger a "stream.offline" event
    ```
    twitch event trigger streamdown -F http://localhost:8888/.netlify/functions/twitch -s secret -t 581268875
    ```
- To create/list/delete Twitch subscriptions, check out the script I added to the test repository at https://github.com/gr2m/handle-twitch-events-using-github-actions/blob/main/scripts/twitch-subscriptions.js

**Comment by gr2m** [comment]
Going live in 30 minutes at https://twitch.tv/gregorcodes
