### ISSUE TITLE
📅 11/14 @ 12:30pm PT - code walkthrough: `nock`

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#53]
💁🏻 **code walkthrough: `nock`**
📅 Sunday, November 14, 2021
🕐 12:30am Pacific Time
🎙️ _no guests_
📍 https://www.twitch.tv/gregorcodes
🏷️ opensource

---

Subscribe to this issues to get a notification before the show begins and a summary after the show concludes.

### code walkthrough: `nock`

I've been a [nock](https://github.com/nock/nock) maintainers for several years now. We received a generous sponsorship a while ago which, with the support of my fellow maintainers, I'm now using to decompose the `nock` code base. You can follow updates at https://github.com/nock/nock/discussions/2247

#### Outline

This will probably be a 3-4h screencast.

- I'll start out finishing the work on issue forms: https://github.com/nock/nock/pull/2248
- After that, I'll dive into the code base to remind myself how it's all working together and what logic should be moved into its own modules

#### TODOs

Before the show

- [x]  30 minute announcement tweet
 (https://twitter.com/gr2m/status/1459973847160016897)
- [x]  30 minute announcement comment
 (https://github.com/gr2m/helpdesk/issues/53#issuecomment-968353676)

When show begins

- [x]      start of show tweet
 (https://twitter.com/gr2m/status/1459982593386971141)
- [x]  comment on issue
 (https://github.com/gr2m/helpdesk/issues/53#issuecomment-968358516)
- [x]  Set twitter profile url
 (https://twitter.com/gr2m)

After the show

- [ ]  Reset twitter profile after the show
- [ ]  recording available tweet

<a name="recording"></a>

#### Recording

_will be added after the show_

<a name="shownotes"></a>

#### Shownotes

_will be added after the show_

**Comment by gr2m** [comment]
Going live in 30 minutes at https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
I'm now live on https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
Here are the two recordings:

1. https://www.twitch.tv/videos/1205654930
2. https://www.twitch.tv/videos/1205809190

I'll post an update at https://github.com/nock/nock/discussions/2247

**Comment by ahmetcaki** [comment]
Satış toptan alışveriş mağazamız İstanbul Beyazıt[Ahmet Çakir] Instagram[karizma.00191]
(+905318950678)
 ahmetcakir8200@gmail.com @gr2m
