### ISSUE TITLE
📅 12/05 @ 12:00pm PT - Refactoring a 10+ years old code base: nock (Part IV)

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#57]
💁🏻 **Refactoring a 10+ years old code base: nock (Part IV)**
📅 Sunday, December 5, 2021
🕐 12:00am Pacific Time
🎙️ _no guests_
📍 https://www.twitch.tv/gregorcodes
🏷️ opensource

---

Subscribe to this issues to get a notification before the show begins and a summary after the show concludes.

### 📅 12/05 @ 12:00pm PT - Refactoring a 10+ years old code base: nock (Part IV)

I will continue my refactoring work from last 3 weeks: #55, #54, #53

A humble version of the `intercept` module is ready and I changed `nock`'s code to use it. Some tests are already passing. This week, I'll try to get as many of the remaining tests to pass as possible, maybe move some tests into the new module where it makes sense.

If we get all existing tests to pass and reach 100% test coverage again, I'll move the internal intercept module to its own repository and publish it as its own npm module.

#### Outline

- Quick recap of what we accomplished last week during https://github.com/gr2m/helpdesk/issues/55
- Make all remaining tests pass, start with these
  - [ ] `tests/test_client_request.js`
  - [ ] `tests/test_request_overrider.js`
  - [ ] `tests/test_abort.js`
  - [ ] `tests/test_allow_unmocked.js`
  - [ ] `tests/test_allow_unmocked_https.js`
  - [ ] `tests/test_events.js`
  - [ ] `tests/test_net_connect.js`
  - [ ] `tests/test_reply_headers.js`
  - [ ] `tests/test_socket.js`
- Refactor the intercept module, in particular the normalization of request options. I have the gut feeling we should just use the `URL` api parse a request string and make sure we set all the properties. Have another look at what the native `http.RequestClient` api is doing.
- Refactor the `nock` codebase. Remove no longer used code and obsolete tests.
- Create the `nock/intercept` repository and move the internal module there
- Make sure the new repository is fully documented and has 100% test coverage
- Setup continuous releases for the new module
- install the new module as dependency of `nock`
- Celebrate the win!

#### TODOs

Before the show

- [x]  30 minute announcement tweet
 (https://twitter.com/gr2m/status/1467576781771317255)
- [x]  30 minute announcement comment
 (https://github.com/gr2m/helpdesk/issues/57#issuecomment-986286783)

When show begins

- [x]      start of show tweet
 (https://twitter.com/gr2m/status/1467584403350114318)
- [x]  comment on issue
 (https://github.com/gr2m/helpdesk/issues/57#issuecomment-986290725)
- [x]  Set twitter profile url
 (https://twitter.com/gr2m)

After the show

- [ ]  Reset twitter profile after the show
- [ ]  recording available tweet

<a name="recording"></a>

#### Recording

_will be added after the show_

<a name="shownotes"></a>

#### Shownotes

_will be added after the show_

**Comment by gr2m** [comment]
Going live in 30 minutes at https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
I'm now live on https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
Here is the repository of `mitm-esm`:
https://github.com/gr2m/mitm-esm

You can install it with `npm install mitm-esm`

**Comment by gr2m** [comment]
Recording: https://www.twitch.tv/videos/1225179586
