### ISSUE TITLE
📅 12/12 @ 12:00pm PT - Refactoring a 10+ years old code base: nock (Part V)

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#58]
💁🏻 **Refactoring a 10+ years old code base: nock (Part V)**
📅 Sunday, December 12, 2021
🕐 12:00am Pacific Time
🎙️ _no guests_
📍 https://www.twitch.tv/gregorcodes
🏷️ automation

---

Subscribe to this issues to get a notification before the show begins and a summary after the show concludes.

### Refactoring a 10+ years old code base: nock (Part V)

I will continue my refactoring work from first 3 weeks: #55, #54, #53

A humble version of the `intercept` module is ready and I changed `nock`'s code to use it. Some tests are already passing. This week, I'll try to get as many of the remaining tests to pass as possible, maybe move some tests into the new module where it makes sense.

If we get all existing tests to pass and reach 100% test coverage again, I'll move the internal intercept module to its own repository and publish it as its own npm module.

#### Outline

- Quick recap of what we accomplished last week during https://github.com/gr2m/helpdesk/issues/55
- Make all remaining tests pass, start with these
  - [x] `tests/test_client_request.js`
  - [x] `tests/test_request_overrider.js`
  - [x] `tests/test_abort.js`
  - [x] `tests/test_allow_unmocked.js`
  - [x] `tests/test_allow_unmocked_https.js`
  - [x] `tests/test_events.js`
  - [ ] `tests/test_net_connect.js`
  - [x] `tests/test_reply_headers.js`
  - [ ] `tests/test_socket.js`
- Refactor the intercept module, in particular the normalization of request options. I have the gut feeling we should just use the `URL` api parse a request string and make sure we set all the properties. Have another look at what the native `http.RequestClient` api is doing.
- Refactor the `nock` codebase. Remove no longer used code and obsolete tests.
- Create the `nock/intercept` repository and move the internal module there
- Make sure the new repository is fully documented and has 100% test coverage
- Setup continuous releases for the new module
- install the new module as dependency of `nock`
- Celebrate the win!

#### TODOs

Before the show

prepare recap of what I've done so far

- [x]  30 minute announcement tweet
 (https://twitter.com/gr2m/status/1470113748614533127)
- [x]  30 minute announcement comment
 (https://github.com/gr2m/helpdesk/issues/58#issuecomment-991956601)

When show begins

- [x]      start of show tweet
 (https://twitter.com/gr2m/status/1470120943292981255)
- [x]  comment on issue
 (https://github.com/gr2m/helpdesk/issues/58#issuecomment-991960773)
- [x]  Set twitter profile url
 (https://twitter.com/gr2m)

After the show

- [x]  Reset twitter profile after the show
- [ ]  recording available tweet

<a name="recording"></a>

#### Recording

_will be added after the show_

<a name="shownotes"></a>

#### Shownotes

_will be added after the show_

**Comment by gr2m** [comment]
I'm now live on https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
All done for today, I hope to finish the remaining tests in the next session
