### ISSUE TITLE
📅 12/12 @ 12:00pm PT - Refactoring a 10+ years old code base: nock (Part VI)

### ISSUE THREAD

**Issue by gr2m** [gr2m/helpdesk#59]
💁🏻 **Refactoring a 10+ years old code base: nock (Part VI)**
📅 Sunday, December 19, 2021
🕐 12:00am Pacific Time
🎙️ _no guests_
📍 https://www.twitch.tv/gregorcodes
🏷️ opensource

---

Subscribe to this issues to get a notification before the show begins and a summary after the show concludes.

### Refactoring a 10+ years old code base: nock (Part VI)

I will continue my refactoring work from the first 4 weeks: #58, #55, #54, #53

I got most of the tests working, but there are still some left.

If we get all existing tests to pass and reach 100% test coverage again, I'll move the internal intercept module to its own repository and publish it as its own npm module.

#### Outline

- Quick recap of what we accomplished so far
- Make remaining tests pass
  - [x] `tests/test_remove_interceptor.js`
  - [x] `tests/test_fake_timer.js`
  - [x] `tests/test_header_matching.js`
  - [x] `tests/test_nock_lifecycle.js`
  - [x] `tests/test_socket.js`
  - [x] `tests/test_net_connect.js`
  - [x] `tests/test_back.js`
  - [x] `tests/test_back_filters.js`
  - [x] `tests/test_recorder.js`
  - [x] make recorder and nock back use the new intercept module
  - [ ] make tests pass again: `tests/test_recorder.js`, `tests/test_back.js`, `tests/test_back_filters.js`
- Refactor the intercept module, in particular the normalization of request options. I have the gut feeling we should just use the `URL` api to parse a request string and make sure we set all the properties. Have another look at what the native `http.RequestClient` api is doing.
- Refactor the `nock` codebase. Remove no longer used code and obsolete tests.
- Create the `nock/intercept` repository and move the internal module there
- Make sure the new repository is fully documented and has 100% test coverage
- Setup continuous releases for the new module
- install the new module as dependency of `nock`
- Celebrate the win!

#### TODOs

Before the show

- [x]  30 minute announcement tweet
 (https://twitter.com/gr2m/status/1472650703944527886)
- [x]  30 minute announcement comment
 (https://github.com/gr2m/helpdesk/issues/59#issuecomment-997447868)

When show begins

- [x]      start of show tweet
 (https://twitter.com/gr2m/status/1472657480480137220)
- [x]  comment on issue
 (https://github.com/gr2m/helpdesk/issues/59#issuecomment-997451584)
- [x]  Set twitter profile url
 (https://twitter.com/gr2m)

After the show

- [x]  Reset twitter profile after the show
- [x]  recording available tweet

<a name="recording"></a>

#### Recording

[_will be added after the show_](https://www.twitch.tv/videos/1238035345)

<a name="shownotes"></a>

#### Shownotes

_will be added after the show_

**Comment by gr2m** [comment]
Going live in 30 minutes at https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
I'm now live on https://twitch.tv/gregorcodes

**Comment by gr2m** [comment]
And we are done. Recording is available at https://www.twitch.tv/videos/1238035345
